name: SAST Scan
jobs:
  sast-scan:
    uses: splunk/sast-scanning/.github/workflows/sast-scan.yml@main
    secrets: inherit
    with:
      block_mode: "policy"
    variables:
      SEMGREP_RULE_EXCLUDE: "splunk.aws-ec2-launch-template-metadata-service-v1-enabled,terraform.aws.security.aws-ec2-launch-template-metadata-service-v1-enabled.aws-ec2-launch-template-metadata-service-v1-enabled"
on:
  push:
    branches:
      - "main" 
  pull_request:
    branches: [main]
